# Generated by Django 3.2.5 on 2022-02-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0003_auto_20220221_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='chead0',
            field=models.CharField(default='', max_length=50000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='head0',
            field=models.CharField(default='', max_length=50000),
        ),
    ]
