# Generated by Django 3.2.5 on 2022-02-22 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0005_rename_tilte_blogpost_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='title',
            new_name='tilte',
        ),
    ]
